title = "nais blog"
theme = "hugo-tailwind-journal"
pygmentsCodeFences = true
pygmentsUseClasses = true
uglyurls = true

[taxonomies]
    tag = "tags"

[permalinks]
    posts = "/posts/:year/:month/:title/"

[params]
    author = "NAIS-team"
    avatar = "images/nais-logo.png"
    description = "nais blog"

