title = "Nais Blog"
theme = "hugo-tailwind-journal"
pygmentsCodeFences = true
pygmentsUseClasses = true
uglyurls = true

[taxonomies]
    tag = "tags"

[permalinks]
    posts = "/posts/:year/:month/:title/"

[params]
    author = "Nais-teamet"
    avatar = "images/nais-logo.png"
    description = "Løst og fast fra teamet bak nais.io"
    tagline = "Løst og fast fra teamet bak nais.io"

