name: main

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Clear old content
        run: rm -rf docs/*
      - name: Run Hugo build to create new content
        uses: klakegg/actions-hugo@1.0.0
        with:
          command: -d docs
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add generated docs

