name: main

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.104.2'
          extended: true
      - name: Build
        run: hugo
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action user"
          mv public docs
          git add -f docs
          git commit -m "Add generated content"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: export
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
