name: main

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Clear old content
        run: rm -rf docs/*
      - name: Run Hugo build to create new content
        uses: klakegg/actions-hugo@1.0.0
        with:
          command: -d docs
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action user"
          git add ./docs
          git commit -m "Add generated docs"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

